/**
 * 
 */
package co.orffosoft.enums;

/**
 * @author pratap kumar sahu
 *
 */
public enum AppConfigEnum {

	OPERATION_PLAN_MARGIN_PERCENTAGE,
	JOBAPPLICATION_PHOTO_UPLOAD_PATH,
	JOBAPPLICATION_HALLTICKET_UPLOAD_PATH,
	FILE_MOVEMENT_LEVEL_SIZE,
	DATE_FORMAT,
	ECOMM_IMAGE_PARENT_DIR,
	DA_CALCULATION_PERCENTAGE,
	PF_CALCULATION_PERCENTAGE,
	GRATUITY_CALCULATION_PERCENTAGE,PROMOTION_ACCEPTENCE_OPTIONS,
	PAYROLL_RETIREMENT_BENEFIT_FUND_SCHEME_AMOUNT,
	PAYROLL_LABOUR_WELFARE_FUND_CADRE_LIST,
	PAYROLL_LABOUR_WELFARE_FUND_AMOUNT,
	PAYROLL_FAMILY_BENEFIT_FUND_SCHEME_AMOUNT,EMPLOYEE_RESIGNATION_VRS_UPLOAD_PATH,
	ECOMM_FILES_PARENT_DIR,
	ECOMM_CAREER_PERSONAL,
	ECOMM_CAREER_ADDITIONALINFO,
	ECOMM_CAREER_QUALIFICATION,
	ECOMM_CAREER_WORKEXPERIENCE,
	ECOMM_CAREER_CERTIFICATES,
	ECOMM_USER_PROFILE_IMAGES,
	ECOMM_USER_PROOF_IMAGES,
	ECOMM_USER_MADE_TO_ORDER,
	ORG_NAME_FOR_BILL,
	BILL_START_DATE,
	ENABLE_SET_BILL_DATE,
	INITIAL_STOCK_UPLOAD_PATH
	
}
