package co.orffosoft.enums;

public enum StockTransferType {
	SOCIETY_OUTWARD, 
	WAREHOUSE_INWARD, WAREHOUSE_OUTWARD, 
	DISTRIB_INWARD, DISTRIB_OUTWARD, 
	SHOWROOM_INWARD, SHOWROOM_OUTWARD, 
	INSPECTION_INWARD, INSPECTION_OUTWARD, 
	ISSR_INWARD, ISSR_OUTWARD,
	EXPORT_WAREHOUSE_INWARD, EXPORT_WAREHOUSE_OUTWARD,
	PRINTING_WAREHOUSE_INWARD, PRINTING_WAREHOUSE_OUTWARD,
	STOCK_ITEM_INWARD,STOCK_ITEM_PO_BASED,
	TESTING_INWARD_STOCKTRANSFER,TESTING_INWARD_MANUAL,	
	STOCK_ITEM_OUTWARD,YARN_INWARD,YARN_OUTWARD,PRODUCT_WAREHOUSE
}
